FROM python:3.14.2-alpine

WORKDIR /app

RUN apk add --no-cache ca-certificates sqlite \
    && update-ca-certificates

RUN python3 -m ensurepip --upgrade \
    && python3 -m pip install --no-cache-dir --upgrade pip

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy source
COPY src /app/src

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

EXPOSE 9617

CMD ["python3", "-m", "pihole_sqlite_exporter.exporter"]
